version: "3"

services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    image: jonasal/nginx-certbot:6.2.0
    restart: always
    environment:
      CERTBOT_EMAIL: "182848600+Lilllllly06@users.noreply.github.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
